package com.breakinblocks.nautec.network;

import com.breakinblocks.nautec.Nautec;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.network.event.RegisterPayloadHandlersEvent;
import net.neoforged.neoforge.network.registration.PayloadRegistrar;

@EventBusSubscriber(modid = Nautec.MODID)
public class NetworkEvents {
    @SubscribeEvent
    public static void registerPayloads(final RegisterPayloadHandlersEvent event) {
        final PayloadRegistrar registrar = event.registrar("11");
        registrar.playToClient(
                AugmentationStationSyncPayload.TYPE,
                AugmentationStationSyncPayload.STREAM_CODEC,
                AugmentationStationSyncPayload::handle
        );
        registrar.playToServer(
                SetSpawnerFilterPayload.TYPE,
                SetSpawnerFilterPayload.STREAM_CODEC,
                SetSpawnerFilterPayload::handle
        );
        registrar.playToClient(
                OpenCharmScreenPayload.TYPE,
                OpenCharmScreenPayload.STREAM_CODEC,
                OpenCharmScreenPayload::handle
        );
        registrar.playToServer(
                SetCharmPriorityPayload.TYPE,
                SetCharmPriorityPayload.STREAM_CODEC,
                SetCharmPriorityPayload::handle
        );
        registrar.playToServer(
                OpenResonanceAugmentPayload.TYPE,
                OpenResonanceAugmentPayload.STREAM_CODEC,
                OpenResonanceAugmentPayload::handle
        );
        registrar.playToServer(
                ReplicatorModePayload.TYPE,
                ReplicatorModePayload.STREAM_CODEC,
                ReplicatorModePayload::handle
        );
        registrar.playToServer(
                BubbleAnchorTogglePayload.TYPE,
                BubbleAnchorTogglePayload.STREAM_CODEC,
                BubbleAnchorTogglePayload::handle
        );
        registrar.playToServer(
                SetConverterRatePayload.TYPE,
                SetConverterRatePayload.STREAM_CODEC,
                SetConverterRatePayload::handle
        );
        registrar.playToServer(
                DistributorEditPayload.TYPE,
                DistributorEditPayload.STREAM_CODEC,
                DistributorEditPayload::handle
        );
        registrar.playToServer(
                ConduitTapEditPayload.TYPE,
                ConduitTapEditPayload.STREAM_CODEC,
                ConduitTapEditPayload::handle
        );
        registrar.playToClient(
                ConduitTapSyncPayload.TYPE,
                ConduitTapSyncPayload.STREAM_CODEC,
                ConduitTapSyncPayload::handle
        );
        registrar.playToServer(
                SetGhostInputPayload.TYPE,
                SetGhostInputPayload.STREAM_CODEC,
                SetGhostInputPayload::handle
        );
        registrar.playToServer(
                SetSideConfigPayload.TYPE,
                SetSideConfigPayload.STREAM_CODEC,
                SetSideConfigPayload::handle
        );
        registrar.playToServer(
                KeyPressedPayload.TYPE,
                KeyPressedPayload.STREAM_CODEC,
                KeyPressedPayload::keyPressedAction
        );
        registrar.playToServer(
                BacteriaSlotClickedPayload.TYPE,
                BacteriaSlotClickedPayload.STREAM_CODEC,
                BacteriaSlotClickedPayload::handle
        );
        registrar.playToClient(
                SyncAugmentPayload.TYPE,
                SyncAugmentPayload.STREAM_CODEC,
                SyncAugmentPayload::setAugmentDataAction
        );
        registrar.playToClient(
                SetCooldownPayload.TYPE,
                SetCooldownPayload.STREAM_CODEC,
                SetCooldownPayload::setCooldownAction
        );
        registrar.playToClient(
                TidalShockwavePayload.TYPE,
                TidalShockwavePayload.STREAM_CODEC,
                TidalShockwavePayload::handle
        );
        registrar.playToServer(
                StartAugmentationPayload.TYPE,
                StartAugmentationPayload.STREAM_CODEC,
                StartAugmentationPayload::startAugmentation
        );
        registrar.playToClient(
                OpenFishingMinigamePayload.TYPE,
                OpenFishingMinigamePayload.STREAM_CODEC,
                OpenFishingMinigamePayload::handle
        );
        registrar.playToServer(
                FishingMinigameResultPayload.TYPE,
                FishingMinigameResultPayload.STREAM_CODEC,
                FishingMinigameResultPayload::handle
        );
        registrar.playToClient(
                OpenGatewayScreenPayload.TYPE,
                OpenGatewayScreenPayload.STREAM_CODEC,
                OpenGatewayScreenPayload::handle
        );
        registrar.playToServer(
                SetGatewayAddressPayload.TYPE,
                SetGatewayAddressPayload.STREAM_CODEC,
                SetGatewayAddressPayload::handle
        );
        registrar.playToServer(
                SubmarineAbilityPayload.TYPE,
                SubmarineAbilityPayload.STREAM_CODEC,
                SubmarineAbilityPayload::handle
        );
        registrar.playToServer(
                SubmarineLaserPayload.TYPE,
                SubmarineLaserPayload.STREAM_CODEC,
                SubmarineLaserPayload::handle
        );
        registrar.playToServer(
                ResonanceActionPayload.TYPE,
                ResonanceActionPayload.STREAM_CODEC,
                ResonanceActionPayload::handle
        );
        registrar.playToClient(
                ResonanceSyncPayload.TYPE,
                ResonanceSyncPayload.STREAM_CODEC,
                ResonanceSyncPayload::handle
        );
        registrar.playToServer(
                ToggleWaveJetLightPayload.TYPE,
                ToggleWaveJetLightPayload.STREAM_CODEC,
                ToggleWaveJetLightPayload::handle
        );
        registrar.playToClient(
                SubmarineCooldownPayload.TYPE,
                SubmarineCooldownPayload.STREAM_CODEC,
                SubmarineCooldownPayload::handle
        );
        registrar.playToClient(
                SonarPingPayload.TYPE,
                SonarPingPayload.STREAM_CODEC,
                SonarPingPayload::handle
        );
        registrar.playToClient(
                TeleportFxPayload.TYPE,
                TeleportFxPayload.STREAM_CODEC,
                TeleportFxPayload::handle
        );
        registrar.playToClient(
                ClearAugmentPayload.TYPE,
                ClearAugmentPayload.STREAM_CODEC,
                ClearAugmentPayload::clearAugmentAction
        );
    }
}
