package com.breakinblocks.nautec.datagen;

import com.breakinblocks.nautec.Nautec;
import com.breakinblocks.nautec.data.generated.BacteriaMaterials;
import com.breakinblocks.nautec.registries.NTBlocks;
import com.breakinblocks.nautec.registries.NTFluids;
import com.breakinblocks.nautec.utils.Utils;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceKey;
import net.neoforged.neoforge.common.data.LanguageProvider;
import net.neoforged.neoforge.fluids.FluidType;
import net.neoforged.neoforge.registries.NeoForgeRegistries;

import java.util.function.Supplier;

import static com.breakinblocks.nautec.registries.NTBacterias.*;
import static com.breakinblocks.nautec.registries.NTItems.*;

public class EnUsProvider extends LanguageProvider {
    public EnUsProvider(PackOutput output) {
        super(output, Nautec.MODID, "en_us");
    }

    @Override
    protected void addTranslations() {
        curiosIdent("prism_monocle", "Monocle");
        curiosIdent("battery", "Battery");

        addItem(LUMINOUS_MEMBRANE, "Luminous Membrane");
        addItem(CHITIN_PLATE, "Chitin Plate");
        addItem(ABYSSAL_ORGAN, "Abyssal Organ");
        addItem(SILT_SKIPPER, "Silt Skipper");
        addItem(SILT_SKIPPER_BUCKET, "Bucket of Silt Skipper");
        addItem(SILT_SKIPPER_SPAWN_EGG, "Silt Skipper Spawn Egg");
        addItem(LANTERN_JELLY_SPAWN_EGG, "Lantern Jelly Spawn Egg");
        addItem(VENT_CRAWLER_SPAWN_EGG, "Vent Crawler Spawn Egg");
        addItem(ABYSSAL_MAW_SPAWN_EGG, "Abyssal Maw Spawn Egg");

        add("nautec.jei.category.pressure_forging", "Pressure Forging");
        add("nautec.jei.category.resonance_crafting", "Resonance Crafting");
        add("nautec.jei.pressure_requirements", "%s water blocks, %s AP");
        add("nautec.jei.pressure_depth", "Y \u2264 %s, under source water");
        add("nautec.jei.resonance_critical", "Crafts at critical charge");
        add("augment_type.nautec.abyssal_eyes", "Abyssal Eyes");
        add("augment_type.nautec.photophore_skin", "Photophore Skin");
        add("augment_type.nautec.vent_carapace", "Vent Carapace");

        addItem(WAVE_JET, "Wave Jet");
        add("nautec.wave_jet.needs_water", "The Wave Jet only bites under water");
        add("nautec.wave_jet.both_hands", "The Wave Jet takes both hands");
        add("nautec.wave_jet.spotlight", "Spotlight: ");
        add("nautec.wave_jet.spotlight_hint", "Toggle the spotlight with your Wave Jet key (F by default) while holding it");
        addItem(ATLANTEAN_RIFLE, "Atlantean Rifle");
        add("nautec.atlantean_rifle.hint", "Hold use to spin up and fire a particle beam");
        add("nautec.atlantean_rifle.ramp", "The beam bites harder and drinks more power the longer you hold it");
        add("nautec.atlantean_rifle.no_power", "The Atlantean Rifle has no charge");
        add("nautec.atlantean_rifle.infinity", "Infinity halves the power draw");
        add("death.attack.nautec.particle_beam", "%1$s was vaporized by a particle beam.");
        add("death.attack.nautec.particle_beam.player", "%1$s was vaporized by a particle beam.");
        add("death.attack.nautec.particle_beam.item", "%1$s was vaporized by a particle beam.");
        add("death.attack.nautec.tidal_shockwave", "%1$s was swept away by %2$s's tidal shockwave");
        add("death.attack.nautec.tidal_shockwave.player", "%1$s was swept away by a tidal shockwave");
        add("death.attack.nautec.tidal_shockwave.item", "%1$s was swept away by %2$s wielding %3$s");
        addItem(NAUTEC_FISHING_ROD, "Prismatic Fishing Rod");
        add("nautec.fishing_minigame.timing_bar", "Something is biting");
        add("nautec.fishing_minigame.rhythm", "It is fighting you");
        add("nautec.fishing_minigame.hold", "It is running with the line");
        add("nautec.fishing_minigame.prompt.timing_bar", "Strike when the marker hits the green");
        add("nautec.fishing_minigame.prompt.rhythm", "Strike on all three marks");
        add("nautec.fishing_minigame.prompt.hold", "Hold through the green, then let go");
        add("nautec.fishing_minigame.missed", "It slipped the hook");
        add("nautec.fishing_minigame.hooked", "Hooked it");

        addItem(SUBMARINE, "Sea Scout");
        add("entity.nautec.submarine", "Sea Scout");
        add("nautec.submarine.controls", "W/S throttle, mouse steers, Space rises, C dives");
        add("nautec.submarine.aim", "Hold use to look around without steering");
        add("nautec.submarine.oxygen", "Sealed and powered, it keeps its crew breathing");
        add("nautec.submarine.hull", "Hull integrity:");
        add("nautec.submarine.breached", "The hull is breached. Repair it on an anvil before launching");
        add("nautec.submarine.needs_water", "The Sea Scout needs open water to launch into");
        add("nautec.submarine.modules", "Sea Scout Modules");
        add("nautec.submarine.modules.installed", "Installed: %s");

        addItem(SOLAR_MODULE, "Solar Module");
        addItem(BOOSTER_MODULE, "Booster Module");
        addItem(STEALTH_MODULE, "Stealth Module");
        addItem(ARMOR_MODULE, "Armour Module");
        addItem(SONAR_MODULE, "Sonar Module");
        addItem(SHIELD_MODULE, "Shield Module");
        addItem(IMPULSE_LASER_MODULE, "Impulse Laser Module");
        addItem(TELEPORT_MODULE, "Teleport Module");
        addItem(FLIGHT_MODULE, "Flight Module");

        add("nautec.submarine.ability.cooldown", "That module is still cycling");
        add("nautec.submarine.ability.no_power", "Not enough power for that module");
        add("nautec.submarine.ability.not_bound", "That teleport module has no anchor bound");
        add("nautec.submarine.ability.destination_blocked", "The anchor is blocked or dry");
        add("effect.nautec.stunned", "Stunned");

        add("advancements.nautec.root.title", "NauTec");
        add("advancements.nautec.root.description", "Lasers, bacteria and the deep ocean");
        add("advancements.nautec.first_beam.title", "Light Under Water");
        add("advancements.nautec.first_beam.description", "Craft a Prismarine Laser Relay");
        add("advancements.nautec.prism_monocle.title", "Through the Lens");
        add("advancements.nautec.prism_monocle.description", "Get a Prism Monocle to read beams and machines");
        add("advancements.nautec.augmentation_station.title", "Some Assembly Required");
        add("advancements.nautec.augmentation_station.description", "Craft an Augmentation Station");
        add("advancements.nautec.prismarine_crystal.title", "Crystal Clear");
        add("advancements.nautec.prismarine_crystal.description", "Find a Prismarine Crystal in a geode under the ocean floor");
        add("advancements.nautec.resonant_shard.title", "Good Vibrations");
        add("advancements.nautec.resonant_shard.description", "Make a Resonant Shard");
        add("advancements.nautec.pressing_the_deep.title", "Under Pressure");
        add("advancements.nautec.pressing_the_deep.description", "Press a Flawless Prismarine Crystal and some Deep Steel Plating");
        add("advancements.nautec.atlantean_rifle.title", "Locked and Loaded");
        add("advancements.nautec.atlantean_rifle.description", "Craft an Atlantean Rifle");
        add("advancements.nautec.particles_accelerated.title", "Particles Accelerated");
        add("advancements.nautec.particles_accelerated.description", "Kill something with the Atlantean Rifle's beam");
        add("advancements.nautec.neptunes_trident.title", "Ruler of the Waves");
        add("advancements.nautec.neptunes_trident.description", "Craft Neptune's Trident");
        add("advancements.nautec.diving_suit.title", "Suited Up");
        add("advancements.nautec.diving_suit.description", "Collect a full Diving Suit");
        add("advancements.nautec.abyssal_trench.title", "Into the Abyss");
        add("advancements.nautec.abyssal_trench.description", "Swim into the Abyssal Trench");
        add("advancements.nautec.deep_survey.title", "Deep Survey");
        add("advancements.nautec.deep_survey.description", "Visit every NauTec ocean biome");
        add("advancements.nautec.abyssal_maw.title", "Bigger Fish");
        add("advancements.nautec.abyssal_maw.description", "Kill an Abyssal Maw");
        add("advancements.nautec.prismatic_angler.title", "Prismatic Angler");
        add("advancements.nautec.prismatic_angler.description", "Hook something with the Prismatic Fishing Rod");
        add("advancements.nautec.sea_scout.title", "Sea Scout");
        add("advancements.nautec.sea_scout.description", "Climb aboard a Sea Scout");
        add("advancements.nautec.submarine_flight.title", "Fish Out of Water");
        add("advancements.nautec.submarine_flight.description", "Fly a Sea Scout with a Flight Module");
        add("advancements.nautec.gateway_found.title", "The Ring on the Sea Floor");
        add("advancements.nautec.gateway_found.description", "Find a Gateway ring");
        add("advancements.nautec.gateway_travel.title", "Through the Horizon");
        add("advancements.nautec.gateway_travel.description", "Pass through an open Gateway");
        add("advancements.nautec.sea_lane.title", "Sea Lane");
        add("advancements.nautec.sea_lane.description", "Steer a Sea Scout through a Gateway");
        add("advancements.nautec.ring_maker.title", "Ring Maker");
        add("advancements.nautec.ring_maker.description", "Get a Gateway of your own");
        add("advancements.nautec.first_culture.title", "Culture Club");
        add("advancements.nautec.first_culture.description", "Graft bacteria into a Petri Dish with a Grafting Tool");
        add("advancements.nautec.bacteria_mutation.title", "Survival of the Fittest");
        add("advancements.nautec.bacteria_mutation.description", "Mutate a strain of bacteria in a Mutator");
        add("advancements.nautec.industrial_bio_reactor.title", "Living Factory");
        add("advancements.nautec.industrial_bio_reactor.description", "Craft an Industrial Bio Reactor");

        add("nautec.gateway.title", "Gateway Address");
        add("nautec.gateway.apply", "Set");
        add("nautec.gateway.cancel", "Cancel");
        add("nautec.gateway.no_change", "Pick a colour for each of the four address chevrons");
        add("nautec.gateway.free", "Changing the address is free");
        add("nautec.gateway.status.open", "Open");
        add("nautec.gateway.status.ready", "Ready: opens when a player or submarine comes within 12 blocks");
        add("nautec.gateway.status.unlinked", "Idle: no other ring has this address");
        add("nautec.gateway.status.no_power", "No power: aim a laser at the Gateway");
        add("nautec.gateway.force_built", "Ring built: blocks in the way were cleared");
        add("nautec.gateway.status.charging", "Charging: opens once it holds %s AP, then uses %s AP/t while open");
        add("nautec.gateway.status.redstone", "Held shut by a redstone signal");
        add("nautec.gateway.status.wild", "Wild ring: builds its far end on the first trip if it has none");
        add("nautec.gateway.status.building", "Building its ring");
        add("nautec.gateway.status.unformed", "No ring: build Gateway Ring Segments around it and use a wrench");
        add("nautec.gateway.status.blocked", "Ring blocked at %s %s %s: clear that block and it finishes building itself");
        add("nautec.gateway.blocked", "The ring has no room to build: a block is in the way at %s %s %s. The ring needs a space 13 wide and 13 tall. Wear a Prism Monocle and look at the Gateway to see every block in the way highlighted in red");
        add("nautec.gateway.power", "Power: %s / %s AP, uses %s AP/t while open");
        add("nautec.gateway.packed", "Packed ring: place it to rebuild the whole ring facing you");
        add("nautec.gateway.packed_wild", "Wild ring: still builds its far end on the first trip if it has none");

        add("subtitles.nautec.submarine.engine", "Sea Scout thrusters churn");
        add("subtitles.nautec.submarine.ambient", "Sea Scout hull hums");
        add("subtitles.nautec.submarine.deploy", "Sea Scout canopy seals");
        add("subtitles.nautec.submarine.stow", "Sea Scout canopy opens");
        add("subtitles.nautec.submarine.sonar_ping", "Sonar pings");
        add("subtitles.nautec.submarine.boost", "Thrusters surge");
        add("subtitles.nautec.submarine.shield_pulse", "Shield discharges");
        add("subtitles.nautec.submarine.stealth", "Hull goes quiet");
        add("subtitles.nautec.submarine.laser_loop", "Impulse lasers burn");
        add("subtitles.nautec.submarine.teleport_charge", "Sea Scout folds the water");
        add("subtitles.nautec.submarine.teleport_whoosh", "Sea Scout jumps");
        add("subtitles.nautec.submarine.module_install", "Module seats home");
        add("subtitles.nautec.submarine.hull_damage", "Hull takes a hit");
        add("subtitles.nautec.submarine.low_power", "Power reserve warning");
        add("subtitles.nautec.gateway.ambient", "Gateway hums");
        add("subtitles.nautec.gateway.travel", "Gateway swallows");
        add("subtitles.nautec.gateway.recode", "Gateway address set");
        add("subtitles.nautec.gateway.unlinked", "Gateway finds no pair");
        add("subtitles.nautec.resonance.charge", "Resonance Chamber rings");
        add("subtitles.nautec.resonance.craft", "Resonance settles");
        add("subtitles.nautec.resonance.vent", "Resonance Chamber vents");
        add("subtitles.nautec.pressure_forge.work", "Pressure Forge works");
        add("subtitles.nautec.pressure_forge.complete", "Pressure Forge finishes");
        add("subtitles.nautec.dock.clamp", "Dock clamps hull");
        add("subtitles.nautec.dock.release", "Dock releases hull");
        add("subtitles.nautec.optics.hum", "Optics hum");
        add("subtitles.nautec.fuel_cell.burn", "Colony feeds the cell");
        add("subtitles.nautec.wave_jet.start", "Wave Jet spins up");
        add("subtitles.nautec.wave_jet.loop", "Wave Jet drives");
        add("subtitles.nautec.wave_jet.stop", "Wave Jet winds down");
        add("subtitles.nautec.atlantean_rifle.charge", "Atlantean Rifle spins up");
        add("subtitles.nautec.atlantean_rifle.fire", "Particle beam burns");
        add("subtitles.nautec.atlantean_rifle.spark", "Atlantean Rifle crackles");
        add("subtitles.nautec.silt_skipper.ambient", "Silt Skipper bubbles");
        add("subtitles.nautec.silt_skipper.hurt", "Silt Skipper hurts");
        add("subtitles.nautec.silt_skipper.death", "Silt Skipper dies");
        add("subtitles.nautec.silt_skipper.flop", "Silt Skipper flops");
        add("subtitles.nautec.lantern_jelly.ambient", "Lantern Jelly burbles");
        add("subtitles.nautec.lantern_jelly.hurt", "Lantern Jelly hurts");
        add("subtitles.nautec.lantern_jelly.death", "Lantern Jelly dies");
        add("subtitles.nautec.lantern_jelly.pulse", "Lantern Jelly pulses");
        add("subtitles.nautec.vent_crawler.ambient", "Vent Crawler clicks");
        add("subtitles.nautec.vent_crawler.hurt", "Vent Crawler hurts");
        add("subtitles.nautec.vent_crawler.death", "Vent Crawler dies");
        add("subtitles.nautec.vent_crawler.step", "Vent Crawler scuttles");
        add("subtitles.nautec.abyssal_maw.ambient", "Abyssal Maw rumbles");
        add("subtitles.nautec.abyssal_maw.hurt", "Abyssal Maw hurts");
        add("subtitles.nautec.abyssal_maw.death", "Abyssal Maw dies");
        add("subtitles.nautec.abyssal_maw.attack", "Abyssal Maw bites");
        add("key.category.nautec.main", "Nautec");
        add("key.nautec.augment_screen", "Open the Augmentation Screen");
        add("key.nautec.throw_trident", "Throw Trident");
        add("key.nautec.leap", "Leap");
        add("key.nautec.throw_potion", "Throw Potion");
        add("key.nautec.throw_spreading_trident", "Throw Spreading Trident");
        add("key.nautec.activate_laser", "Activate Guardian Eye Augment Laser");
        add("key.nautec.submarine_descend", "Sea Scout Descend");
        add("key.nautec.submarine_ability", "Fire Sea Scout Module");
        add("key.nautec.wave_jet_light", "Toggle Wave Jet Spotlight");
        add("key.nautec.submarine_hud", "Reposition Sea Scout HUD");

        add("nautec.submarine.module.passive", "Passive, works from any slot");
        add("nautec.submarine.module.cost", "Draws %s power per use");
        add("nautec.submarine.module.cooldown", "%s second cooldown");
        add("nautec.submarine.module.solar", "Solar Module");
        add("nautec.submarine.module.solar.desc", "Trickles the hull's cells full again in open sunlit water");
        add("nautec.submarine.module.booster", "Booster Module");
        add("nautec.submarine.module.booster.desc", "Dumps the reserve into the thrusters for a short sprint");
        add("nautec.submarine.module.stealth", "Stealth Module");
        add("nautec.submarine.module.stealth.desc", "Masks the hull so the deep stops noticing it, at the cost of speed");
        add("nautec.submarine.module.armor", "Armour Module");
        add("nautec.submarine.module.armor.desc", "Plates the hull to shrug off heavier hits");
        add("nautec.submarine.module.sonar", "Sonar Module");
        add("nautec.submarine.module.sonar.desc", "Pings the surrounding rock and lights up ore and anything hunting you");
        add("nautec.submarine.module.shield", "Shield Module");
        add("nautec.submarine.module.shield.desc", "Bleeds power to soak damage, and discharges to throw off boarders");
        add("nautec.submarine.module.impulse_laser", "Impulse Laser Module");
        add("nautec.submarine.module.impulse_laser.desc", "Twin prismatic beams that cut whatever the nose is pointed at");
        add("nautec.submarine.module.teleport", "Teleport Module");
        add("nautec.submarine.module.flight", "Flight Module");
        add("nautec.submarine.module.flight.desc", "Lifts the hull out of the water so it flies, half again as fast as it swims");
        add("nautec.submarine.module.teleport.desc", "Folds the water around the hull and drops it at a bound anchor");
        add("nautec.submarine.module.teleport.unbound", "No anchor bound");
        add("nautec.submarine.module.teleport.bound", "Anchor bound to %s");
        add("nautec.submarine.module.teleport.destination", "Anchor: %s in %s");
        add("nautec.submarine.module.teleport.needs_water", "The anchor has to be set in water");

        add("entity.nautec.silt_skipper", "Silt Skipper");
        add("entity.nautec.lantern_jelly", "Lantern Jelly");
        add("entity.nautec.vent_crawler", "Vent Crawler");
        add("entity.nautec.abyssal_maw", "Abyssal Maw");
        add("entity.nautec.neptunes_trident", "Neptune's Trident");

        addBlock("budding_prismarine", "Budding Prismarine");
        addBlock("small_prismarine_bud", "Small Prismarine Bud");
        addBlock("medium_prismarine_bud", "Medium Prismarine Bud");
        addBlock("large_prismarine_bud", "Large Prismarine Bud");
        addBlock("prismarine_cluster", "Prismarine Cluster");
        addBlock("deep_kelp", "Deep Kelp");
        addBlock("deep_kelp_plant", "Deep Kelp Plant");
        addBlock("luminescent_algae", "Luminescent Algae");
        addBlock("prismarine_frond", "Prismarine Frond");
        addBlock("vent_tubeworm", "Vent Tubeworm");
        addBlock("abyssal_coral", "Abyssal Coral");
        addBlock("glow_polyp", "Glow Polyp");

        add("biome.nautec.abyssal_trench", "Abyssal Trench");
        add("biome.nautec.bioluminescent_grove", "Bioluminescent Grove");
        add("biome.nautec.hydrothermal_vents", "Hydrothermal Vents");
        add("biome.nautec.prismarine_reef", "Prismarine Reef");

        add("nautec.creative_tab.main", "NauTec");
        add("nautec.creative_tab.bacteria", "NauTec Bacteria");

        addFluidType(NTFluids.SALT_WATER.getFluidType(), "Salt Water");
        addFluidType(NTFluids.EAS.getFluidType(), "Electrolyte Algae Serum");
        addFluidType(NTFluids.ETCHING_ACID.getFluidType(), "Etching Acid");
        addFluidType(NTFluids.OIL.getFluidType(), "Oil");

        addItem(PRISM_MONOCLE, "Prism Monocle");
        addItem(EYE_OF_THE_SEA, "Eye of the Sea");
        add("nautec.eye_of_the_sea.seeking", "Seeking: %s");
        add("nautec.eye_of_the_sea.cycle_hint", "Sneak right-click to change what it seeks");
        add("nautec.eye_of_the_sea.searching", "The eye hums, searching for %s...");
        add("nautec.eye_of_the_sea.busy", "The eye is still searching");
        add("nautec.eye_of_the_sea.not_found", "No %s within range");
        add("nautec.eye_of_the_sea.target.crystal_geodes", "Crystal Geodes");
        add("nautec.eye_of_the_sea.target.nautec_ruins", "NauTec Ruins");
        add("nautec.eye_of_the_sea.target.gateways", "Gateways");
        add("nautec.eye_of_the_sea.target.ocean_ruins", "Ocean Ruins");
        add("nautec.eye_of_the_sea.target.ocean_monuments", "Ocean Monuments");
        add("entity.nautec.eye_of_the_sea", "Eye of the Sea");
        addItem(AQUARINE_STEEL_INGOT, "Aquarine Steel Ingot");
        addItem(ATLANTIC_GOLD_INGOT, "Atlantic Gold Ingot");
        addItem(ATLANTIC_GOLD_NUGGET, "Atlantic Gold Nugget");
        addItem(NTFluids.SALT_WATER.getDeferredBucket(), "Salt Water Bucket");
        addItem(NTFluids.EAS.getDeferredBucket(), "Electrolyte Algae Serum (EAS) Bucket");
        addItem(NTFluids.OIL.getDeferredBucket(), "Oil Bucket");
        addItem(GLASS_VIAL, "Glass Vial");
        addItem(ELECTROLYTE_ALGAE_SERUM_VIAL, "Electrolyte Algae Serum (EAS) Vial");
        addItem(RUSTY_GEAR, "Rusty Gear");
        addItem(GEAR, "Gear");
        addItem(ANCIENT_VALVE, "Ancient Valve");
        addItem(PETRI_DISH, "Petri Dish");
        addItem(REACTOR_SPEED_UPGRADE, "Reactor Speed Upgrade");
        addItem(REACTOR_YIELD_UPGRADE, "Reactor Yield Upgrade");
        addItem(REACTOR_EFFICIENCY_UPGRADE, "Reactor Efficiency Upgrade");
        addItem(REACTOR_FUSION_UPGRADE, "Reactor Fusion Upgrade");
        addItem(SPAWNER_CONFINEMENT_MATRIX, "Spawner Confinement Matrix");
        addItem(DORMANT_CRYSTAL_SEED, "Dormant Crystal Seed");
        addItem(PRISMARINE_CRYSTAL_SEED, "Prismarine Crystal Seed");
        add("nautec.cultivated_crystal.name", "Cultivated Prismarine Crystal");

        addItem("drowned_lungs", "Drowned Lungs");
        addItem("diving_helmet", "Diving Helmet");
        addItem("diving_chestplate", "Diving Chestplate");
        addItem("diving_leggings", "Diving Leggings");
        addItem("diving_boots", "Diving Boots");
        addItem("aquarine_steel_wrench", "Aquarine Steel Wrench");
        addItem("etching_acid_bucket", "Etching Acid Bucket");
        addItem("aquarine_steel_sword", "Aquarine Steel Sword");
        addItem("aquarine_steel_pickaxe", "Aquarine Steel Pickaxe");
        addItem("aquarine_steel_axe", "Aquarine Steel Axe");
        addItem("aquarine_steel_shovel", "Aquarine Steel Shovel");
        addItem("aquarine_steel_hoe", "Aquarine Steel Hoe");
        addItem("neptunes_trident", "Neptune's Trident");
        addItem("aquarine_steel_helmet", "Aquarine Steel Helmet");
        addItem("aquarine_steel_chestplate", "Aquarine Steel Chestplate");
        addItem("aquarine_steel_leggings", "Aquarine Steel Leggings");
        addItem("aquarine_steel_boots", "Aquarine Steel Boots");
        addItem("dolphin_fin", "Dolphin Fin");
        addItem("broken_whisk", "Broken Whisk");
        addItem("whisk", "Whisk");
        addItem("prismatic_battery", "Prismatic Battery");
        addItem("air_bottle", "Pressurized Air Bottle");
        addItem("aquarine_steel_compound", "Aquarine Steel Compound");
        addItem("prismarine_crystal_shard", "Prismarine Crystal Shard");
        addItem("claw_robot_arm", "Claw Robot Arm");
        addItem("syringe_robot_arm", "Syringe Robot Arm");
        addItem(HYDRAULIC_LEG, "Hydraulic Leg");
        addItem(SERVO_KNEE, "Servo Knee");
        addItem(SHOCK_ABSORBER, "Shock Absorber");
        addItem(TENDON_WEAVE, "Tendon Weave");
        addItem(MAGNETIC_COIL_ARM, "Magnetic Coil Arm");
        addItem(ENDER_COIL_ARM, "Ender Coil Arm");
        addItem(HYDRO_DRILL_ARM, "Hydro Drill Arm");
        addItem(TRIDENT_LAUNCHER_ARM, "Trident Launcher Arm");
        addItem(VOLLEY_TRIDENT_ARM, "Volley Trident Arm");
        addItem(BUOYANCY_TANK, "Buoyancy Tank");
        addItem(AUXILIARY_VENTRICLE, "Auxiliary Ventricle");
        addItem("brown_polymer", "Brown Polymer");
        addItem("cast_iron_ingot", "Cast Iron Ingot");
        addItem("cast_iron_rod", "Cast Iron Rod");
        addItem("cast_iron_nugget", "Cast Iron Nugget");
        addItem("salt", "Salt");
        addItem("damaged_aquatic_chip", "Damaged Aquatic Chip");
        addItem(LASER_CHANNELING_COIL, "Laser Channeling Coil");
        addItem(BURNT_COIL, "Burnt Coil");
        addItem(ELDRITCH_HEART, "Eldritch Heart");
        addItem(GUARDIAN_EYE, "Guardian Eye");
        addItem(VALVE, "Valve");
        addItem(CAST_IRON_COMPOUND, "Cast Iron Compound");
        addItem(GRAFTING_TOOL, "Grafting Tool");
        addItem(PRISMARINE_LENS, "Prismarine Lens");
        addItem(AQUATIC_CHIP, "Aquatic Chip");
        
        addItem("nautec_guide", "Nautec Guide");
        add("nautec_guide.desc.0","Nautec's Guide");
        add("nautec_guide.missing_guideme", "Install GuideMe to read the NauTec guide");

        addBlock("rusty_crate", "Rusty Crate");
        addBlock("polished_prismarine", "Polished Prismarine");
        addBlock("mixer", "Mixer");
        addBlock("long_distance_laser", "Long Distance Laser");
        addBlock("laser_junction", "Laser Junction");
        addBlock("prismarine_crystal", "Prismarine Crystal");
        addBlock("decorative_prismarine_crystal", "Decorative Prismarine Crystal");
        addBlock("decorative_prismarine_crystal_part", "Decorative Prismarine Crystal");
        addBlock("deep_sea_drain_wall", "Deep Sea Drain Wall");
        addBlock("augmentation_station", "Augmentation Station");
        addBlock("aquarine_steel_block", "Aquarine Steel Block");
        addBlock("aquatic_catalyst", "Aquatic Catalyst");
        addBlock("dark_prismarine_pillar", "Dark Prismarine Pillar");
        addBlock("chiseled_dark_prismarine", "Chiseled Dark Prismarine");
        addBlock("crate", "Crate");
        addBlock("prismarine_laser_relay", "Prismarine Laser Relay");
        addBlock("deep_sea_drain", "Deep Sea Drain");
        addBlock("augmentation_station_part", "Augmentation Station");
        addBlock("prismarine_crystal_part", "Prismarine Crystal");
        addBlock("anchor", "Anchor");
        addBlock("oil_barrel", "Oil Barrel");
        addBlock(NTBlocks.AUGMENTATION_STATION_EXTENSION, "Augmentation Station Extension");
        addBlock(NTBlocks.CHARGER, "Charger");
        addBlock(NTBlocks.CONFINED_SPAWNER, "Confined Spawner");
        addBlock(NTBlocks.CRYSTAL_CRADLE, "Crystal Cradle");
        addBlock(NTBlocks.SUBMARINE_DOCK, "Sea Scout Dock");
        addBlock(NTBlocks.PRESSURE_FORGE, "Abyssal Pressure Forge");
        addItem(FLAWLESS_PRISMARINE_CRYSTAL, "Flawless Prismarine Crystal");
        addItem(DEEP_STEEL_PLATING, "Deep Steel Plating");
        addBlock(NTBlocks.GATEWAY, "Gateway");
        addBlock(NTBlocks.GATEWAY_RING, "Gateway Ring Segment");
        addBlock(NTBlocks.GATEWAY_RING_PART, "Gateway Ring");
        addBlock(NTBlocks.RESONANCE_CHAMBER, "Resonance Chamber");
        addItem(RESONANT_SHARD, "Resonant Shard");
        addBlock(NTBlocks.PRISMATIC_MIRROR, "Prismatic Mirror");
        addBlock(NTBlocks.BEAM_SPLITTER, "Beam Splitter");
        addBlock(NTBlocks.FOCUSING_LENS, "Focusing Lens");
        addBlock(NTBlocks.PRISMARINE_SAND, "Prismarine Sand");
        addBlock(NTBlocks.CREATIVE_POWER_SOURCE,"Creative Power Source");
        addBlock(NTBlocks.CREATIVE_ENERGY_SOURCE, "Creative Energy Source");
        addBlock(NTBlocks.ENERGY_CONVERTER, "Energy Converter");
        addBlock(NTBlocks.BACTERIAL_ANALYZER_TOP, "Bacterial Analyzer");
        addBlock(NTBlocks.BIO_REACTOR_PART, "Bio Reactor");
        addBlock(NTBlocks.DRAIN_PART, "Deep Sea Drain");
        addBlock(NTBlocks.MUTATOR, "Mutator");
        addBlock(NTBlocks.INCUBATOR, "Incubator");
        addBlock(NTBlocks.BIO_REACTOR, "Bio Reactor");
        addBlock(NTBlocks.INDUSTRIAL_BIO_REACTOR, "Industrial Bio Reactor");
        addBlock(NTBlocks.INDUSTRIAL_BIO_REACTOR_PART, "Industrial Bio Reactor");
        addBlock(NTBlocks.BACTERIAL_ANALYZER, "Bacterial Analyzer");
        addBlock(NTBlocks.BACTERIAL_FUEL_CELL, "Bacterial Fuel Cell");
        addBlock(NTBlocks.FISHING_STATION, "Fishing Station");
        addBlock(NTBlocks.BACTERIAL_CONTAINMENT_SHIELD, "Bacteria Containment Shield");
        addBlock(NTBlocks.CAST_IRON_BLOCK, "Cast Iron Block");

        add("multiblock.info.failed_to_construct", "Missing or invalid block");
        add("multiblock.info.actual_block", "Block: %s");
        add("multiblock.info.expected_block", "Expected: %s");
        add("multiblock.info.block_pos", "Coordinates: %d, %d, %d");

        add("augment_slot.nautec.head", "Head");
        add("augment_slot.nautec.eyes", "Eyes");
        add("augment_slot.nautec.body", "Body");
        add("augment_slot.nautec.lung", "Lungs");
        add("augment_slot.nautec.left_leg", "Left Leg");
        add("augment_slot.nautec.right_leg", "Right Leg");
        add("augment_slot.nautec.left_arm", "Left Arm");
        add("augment_slot.nautec.right_arm", "Right Arm");
        add("augment_slot.nautec.heart", "Heart");

        add("augment_type.nautec.drowned_lung", "Drowned Lung");
        add("augment_type.nautec.guardian_eye", "Guardian Eye");
        add("augment_type.nautec.dolphin_fin", "Dolphin Fin");
        add("augment_type.nautec.eldritch_heart", "Eldritch Heart");
        add("augment_type.nautec.throw_random_potion", "Random Potion Throwing");
        add("augment_type.nautec.throw_bouncing_trident", "Bouncing Trident");
        add("augment_type.nautec.spreading_trident", "Spreading Trident");
        add("augment_type.nautec.leap", "Leap");
        add("augment_type.nautec.prevent_fall_damage", "Prevent Fall Damage");
        add("augment_type.nautec.step_up", "Step Up");
        add("augment_type.nautec.underwater_mining_speed", "Underwater Mining Speed");
        add("augment_type.nautec.bonus_hearts", "Bonus Hearts");
        add("augment_type.nautec.creative_flight", "Creative Flight");
        add("augment_type.nautec.walking_speed", "Walking Speed");
        add("augment_type.nautec.magnet", "Magnet");
        add("augment_type.nautec.ender_magnet", "Ender Magnet");

        addBlock("oil_fluid", "Oil");
        addBlock("saltwater_fluid", "Salt Water");
        addBlock("eas_fluid", "Electrolyte Algae Serum");
        addBlock("etching_acid_fluid", "Etching Acid");

        add("nautec.air_bottle.fill","Right click a glass bottle on a bubble column to fill with pressurized air");
        add("nautec.air_bottle.craft_msg","Either Craft with Chestplate or drink while wearing chestplate to increase oxygen level");
        add("nautec.bacteria.name", "Name: ");
        add("nautec.bacteria.size", "Size: %s");
        add("nautec.bacteria.stats", "Stats: ");
        add("nautec.bacteria.unknown", "???");
        add("nautec.bacteria.vitality", "Vitality: ");
        add("nautec.bacteria.senescent", "Senescent");
        add("nautec.bacteria.percent", "%s%%");
        add("nautec.bacteria.resource", "  Resource: ");
        add("nautec.bacteria.production_multiplier", "Strain Yield: ");
        add("nautec.bacteria.multiplier_value", "x%s");
        add("nautec.bio_reactor.vitality", "Nutrients: %s seconds left");
        add("nautec.bio_reactor.starving", "No nutrients: the colony is aging");
        add("nautec.bio_reactor.power", "Power: %s / %s AP");
        add("nautec.bio_reactor.upgrades", "Speed x%s, %s items per cycle, %s%% nutrient use");
        add("nautec.reactor_upgrade.speed.effect", "+%s%% production speed per upgrade");
        add("nautec.reactor_upgrade.yield.effect", "+%s item per completed cycle per upgrade");
        add("nautec.reactor_upgrade.efficiency.effect", "-%s%% nutrients used per upgrade (down to %s%%)");
        add("nautec.reactor_upgrade.fusion.effect", "Counts as one Speed, one Yield and one Efficiency Upgrade in a single slot");
        add("nautec.spawner_confinement_matrix.use", "Use on a spawner to confine it");
        add("nautec.spawner_confinement_matrix.power", "A confined spawner runs on %s AP per tick and stores the drops");
        add("nautec.spawner_confinement_matrix.release", "Sneak and use on a confined spawner to release it");
        add("nautec.confined_spawner.status.running", "Running");
        add("nautec.confined_spawner.status.no_power", "No Power");
        add("nautec.confined_spawner.status.full", "Full");
        add("nautec.confined_spawner.status.no_mob", "No Mob");
        add("nautec.confined_spawner.status.filtered", "Filtered");
        add("nautec.confined_spawner.status.running.desc", "Making drops into its storage");
        add("nautec.confined_spawner.status.no_power.desc", "Aim a laser beam into any face to fill its AP buffer");
        add("nautec.confined_spawner.status.full.desc", "Paused until a storage slot is free");
        add("nautec.confined_spawner.status.no_mob.desc", "The confined spawner has no mob set");
        add("nautec.confined_spawner.status.filtered.desc", "The whitelist is empty, so nothing can be made");
        add("nautec.confined_spawner.power_source", "Filled by laser beams into any face");
        add("nautec.confined_spawner.cycle.desc", "Each cycle takes as long as the spawner's spawn delay");
        add("nautec.confined_spawner.filter.right_click", "Right-click with an item to filter by its tags");
        add("nautec.confined_spawner.power", "AP: %s / %s");
        add("nautec.confined_spawner.power_use", "Uses %s AP per tick while running");
        add("nautec.confined_spawner.cycle", "Next spawn: %s%%");
        add("nautec.confined_spawner.filter", "Filter");
        add("nautec.confined_spawner.filter.toggle", "Show or hide the drop filter");
        add("nautec.confined_spawner.whitelist", "Whitelist");
        add("nautec.confined_spawner.blacklist", "Blacklist");
        add("nautec.confined_spawner.whitelist.desc", "Only drops that match a filter are made");
        add("nautec.confined_spawner.blacklist.desc", "Drops that match a filter are never made");
        add("nautec.confined_spawner.mode.click", "Click to switch");
        add("nautec.confined_spawner.filter.tag", "Tag: #%s");
        add("nautec.confined_spawner.filter.exact", "Exact item");
        add("nautec.confined_spawner.filter.cycle", "Right-click to cycle through its tags");
        add("nautec.confined_spawner.filter.clear", "Click with an empty hand to clear");
        add("nautec.confined_spawner.filter.empty", "Click with an item, or drag one in from JEI");
        add("nautec.drain.message.not_formed", "Form the drain with an Aquarine Steel Wrench first");
        add("nautec.drain.message.no_power", "The drain needs more than %s AP per tick to open. It is receiving %s AP.");
        add("nautec.drain.message.opened_idle", "Opening, but it will not pump yet: %s");
        add("nautec.drain.message.moving", "The drain is still moving");
        add("nautec.drain.status.not_formed", "Not formed");
        add("nautec.drain.status.not_formed.desc", "Right-click the centre with an Aquarine Steel Wrench to form it");
        add("nautec.drain.status.no_power", "Not enough power");
        add("nautec.drain.status.no_power.desc", "Aim a stronger beam into the laser port on a middle wall");
        add("nautec.drain.status.closed", "Closed");
        add("nautec.drain.status.closed.desc", "Sneak and right-click it with empty hands to open it");
        add("nautec.drain.status.opening", "Opening");
        add("nautec.drain.status.opening.desc", "The valve turns, then the lid opens");
        add("nautec.drain.status.closing", "Closing");
        add("nautec.drain.status.closing.desc", "The lid closes, then the valve turns back");
        add("nautec.drain.status.no_water", "No water above");
        add("nautec.drain.status.no_water.desc", "All nine blocks directly above the drain must be water");
        add("nautec.drain.status.not_ocean", "Not in an ocean");
        add("nautec.drain.status.not_ocean.desc", "The drain or the water above it must be in an ocean biome");
        add("nautec.drain.status.full", "Tank full");
        add("nautec.drain.status.full.desc", "Pipe Salt Water out of the bottom, or fill a Bucket from it");
        add("nautec.drain.status.pumping", "Pumping Salt Water");
        add("nautec.drain.status.pumping.desc", "Pumping Salt Water into its tank");
        add("nautec.jade.drain.power", "Power: %s AP (needs more than %s)");
        add("nautec.crystal_seed.dormant.tooltip", "Awaken it in a Resonance Chamber at purity 3.0");
        add("nautec.crystal_seed.awakened.tooltip", "Set it in a Crystal Cradle and feed the cradle high-purity laser power");
        add("nautec.cultivated_crystal.tooltip.place", "Needs six blocks of free space to place");
        add("nautec.cultivated_crystal.tooltip.move", "Sneak and right-click it with a wrench to pick it up again");
        add("nautec.cultivated_crystal.natural", "This crystal grew wild and is rooted in place. Only cultivated crystals can be moved");
        add("nautec.crystal_cradle.tooltip.seeded", "Holds a seed, %s%% grown (%s / %s AP)");
        add("nautec.crystal_cradle.tooltip.empty", "Grows a Prismarine Crystal Seed into a crystal you can move");
        add("nautec.crystal_cradle.message.occupied", "The cradle already holds a seed");
        add("nautec.crystal_cradle.message.dormant", "This seed is dormant. Awaken it in a Resonance Chamber at purity 3.0 first");
        add("nautec.crystal_cradle.message.growing", "The seed has started growing. Break the cradle to move it; it keeps the seed and its growth");
        add("nautec.crystal_cradle.status.empty", "No seed");
        add("nautec.crystal_cradle.status.empty.desc", "Right-click with a Prismarine Crystal Seed to set one");
        add("nautec.crystal_cradle.status.blocked", "No room to grow");
        add("nautec.crystal_cradle.status.blocked.desc", "Clear the six blocks above the cradle; air or water is fine");
        add("nautec.crystal_cradle.status.no_power", "No power");
        add("nautec.crystal_cradle.status.no_power.desc", "Aim a laser beam into any side of the cradle");
        add("nautec.crystal_cradle.status.low_purity", "Beam purity too low");
        add("nautec.crystal_cradle.status.low_purity.desc", "Only beams at or above the purity shown below grow the seed");
        add("nautec.crystal_cradle.status.growing", "Growing");
        add("nautec.crystal_cradle.status.growing.desc", "Turning laser power into crystal");
        add("nautec.jade.crystal_cradle.growth", "Growth: %s%% (%s / %s AP)");
        add("nautec.jade.crystal_cradle.beam", "Beam: %s AP at purity %s (needs %s)");
        add("nautec.jade.crystal_cradle.remaining", "About %s minutes left at this power");
        add("nautec.jade.crystal.cultivated", "Cultivated: sneak and right-click with a wrench to move it");
        add("nautec.jade.crystal.natural", "Natural: rooted in place");
        add("nautec.jei.crystal_seed", "Craft a Dormant Crystal Seed, then awaken it in a Resonance Chamber at purity 3.0. Set the awakened seed in a Crystal Cradle.");
        add("nautec.jei.crystal_cradle", "Feed the cradle laser beams of purity 2.0 or higher. After %s AP the seed becomes a Cultivated Prismarine Crystal standing on the cradle, which works like a natural one and can be moved with a wrench.");
        add("nautec.jade.confined_spawner.mob", "Mob: %s");
        add("nautec.jade.confined_spawner.running", "Running");
        add("nautec.jade.confined_spawner.stopped", "Stopped");
        add("nautec.reactor_upgrade.power", "Multiplies reactor AP draw by %s");
        add("nautec.bacteria.hint.shift", "Shift");
        add("nautec.bacteria.hint.control", "Control");
        add("nautec.bacteria.hint.and", " and ");
        add("nautec.bacteria.stat.growth_rate", "Growth Rate");
        add("nautec.bacteria.stat.mutation_resistance", "Mutation Resistance");
        add("nautec.bacteria.stat.production_rate", "Production Rate");
        add("nautec.bacteria.stat.lifespan", "Lifespan");

        add("nautec.monocle.power", "Power: %s");
        add("nautec.monocle.purity", "Purity: %s");
        add("nautec.monocle.duration", "Duration: %s");
        add("nautec.monocle.no_colony", "No colony");
        add("nautec.monocle.output", "Output: %s AP/t");
        add("nautec.monocle.fuel", "Fuel: %s");
        add("nautec.monocle.address", "Address: ");
        add("nautec.monocle.fluid_stored", "Fluid Stored: %s");
        add("nautec.monocle.not_pressurised", "Not under pressure: needs y %s or lower with %s blocks of water above");
        add("nautec.monocle.pressurised", "Under pressure");
        add("nautec.monocle.acid", "Acid: %s mb");
        add("nautec.monocle.cracked", "Cracked, cooling down");
        add("nautec.monocle.charge", "Charge: %s%%");
        add("nautec.monocle.ceiling", "Ceiling: %s");
        add("nautec.monocle.dock.occupied", "Sea Scout docked");
        add("nautec.monocle.dock.empty", "No Sea Scout on the pad");

        add("nautec.jade.status.burning", "Status: Burning");
        add("nautec.jade.status.waiting", "Status: Waiting for receiver");
        add("nautec.jade.status.no_fuel", "Status: No fuel");
        add("nautec.jade.receiver.connected", "Receiver: %s, %s");
        add("nautec.jade.receiver.wrong_side", "Receiver: %s is facing the wrong way");
        add("nautec.jade.receiver.blocked", "Receiver: beam blocked by %s");
        add("nautec.jade.receiver.no_target", "Receiver: none within %s blocks");
        add("nautec.jade.catalyst.details", "Sneak and right-click with an empty hand for details");

        add("nautec.catalyst.diagnostics.header", "Aquatic Catalyst");
        add("nautec.catalyst.diagnostics.fuel", "Fuel: %sx %s");
        add("nautec.catalyst.diagnostics.fuel.empty", "Fuel: empty. Right-click it with prismarine shards, prismarine crystals or crystal shards.");
        add("nautec.catalyst.diagnostics.emitter", "Emitter: the lens face, firing %s");
        add("nautec.catalyst.diagnostics.beam.connected", "Beam: connected to %s, %s");
        add("nautec.catalyst.diagnostics.beam.wrong_side", "Beam: %s is %s, but it does not take a beam from this side");
        add("nautec.catalyst.diagnostics.beam.blocked", "Beam: blocked by %s, %s");
        add("nautec.catalyst.diagnostics.beam.no_target", "Beam: no laser receiver within %s blocks %s");
        add("nautec.catalyst.diagnostics.hint.wrong_side", "Turn it with an Aquarine Steel Wrench so its input faces this catalyst. A relay takes its beam in at the back.");
        add("nautec.catalyst.diagnostics.hint.blocked", "A beam needs a clear path. Move that block, or put the receiver in front of it.");
        add("nautec.catalyst.diagnostics.hint.no_target", "Put a machine, relay or optic in line with the lens face, or turn the catalyst with an Aquarine Steel Wrench.");
        add("nautec.catalyst.diagnostics.status.burning", "Status: burning, sending %s AP/t");
        add("nautec.catalyst.diagnostics.status.waiting", "Status: waiting for a receiver. Fuel is held until one is connected.");
        add("nautec.catalyst.diagnostics.status.idle", "Status: idle, no fuel loaded");
        add("nautec.catalyst.distance.one", "1 block %s");
        add("nautec.catalyst.distance", "%s blocks %s");
        add("nautec.direction.north", "north");
        add("nautec.direction.south", "south");
        add("nautec.direction.east", "east");
        add("nautec.direction.west", "west");
        add("nautec.direction.up", "up");
        add("nautec.direction.down", "down");
        add("nautec.jade.processing", "Processing: %sx %s");
        add("nautec.jade.remaining_duration", "Remaining Duration: %s ticks");
        add("nautec.jade.transferring", "Transferring: %s AP/T");
        add("nautec.crate.rusted_shut", "This crate is rusted shut. Drop it in Etching Acid to clean it.");
        add("nautec.crate.rusted_tooltip", "Rusted shut: drop it in Etching Acid to clean it into a Crate");
        add("nautec.jade.rusted_shut", "Rusted shut: clean it in Etching Acid");
        add("nautec.jade.inputs", "Inputs: %s");
        add("nautec.jade.outputs", "Outputs: %s");
        add("nautec.jade.fluid_input", "Fluid Input: %s - %s mB");
        add("nautec.jade.fluid_output", "Fluid Output: %s - %s mB");
        add("nautec.jade.mixing_progress", "Mixing Progress: %s / %s ticks");
        add("nautec.jade.energy", "Energy: %s AP");

        add("nautec.jei.power_per_tick", "Power per tick: %s AP/t");
        add("nautec.jei.total_power", "Total Power amount: %s AP");
        add("nautec.jei.duration_ticks", "Duration: %s");
        add("nautec.jei.purity", "Purity: %s");
        add("nautec.jei.purity_value", "%s purity");
        add("nautec.jei.seconds", "%ss");
        add("nautec.jei.only_in", "Only In: %s");
        add("nautec.jei.growth", "Growth: %s");
        add("nautec.jei.production", "Production: %s - %s");
        add("nautec.jei.production_inherited", "Production: inherited from parent strain");
        add("nautec.jei.production_multiplier", "Strain Yield: x%s");
        add("nautec.jei.colony_feeding.vitality", "+%s vitality ticks (%ss)");
        add("nautec.jei.colony_feeding.any", "Any strain");
        add("nautec.jei.colony_feeding.tag", "Strains in %s");
        add("nautec.jei.colony_feeding.strain", "Strain %s");
        add("nautec.jei.info.prismarine_crystal_shard", "Prismarine Crystal Shards are pristine crystals, capable of channeling power like no other material. They can be obtained by breaking a prismarine crystal using an Aquarine Steel Pickaxe with its ability enabled.");
        add("nautec.jei.info.machine_parts", "These ancient machine components can be found in chests and are dropped by underwater mobs. Once you reach a Crystal Geode you can make them yourself: Gears from a Cast Iron Block in a purity 2.5 beam, Valves and Whisks at the crafting table, and Burnt Coils and Aquatic Chips in the Mixer.");

        add("nautec.augmentation_station.apply", "Apply");
        add("nautec.augment.empty_slot", "No Augment in slot");
        add("nautec.augment_viewer.title", "Augments");
        add("nautec.submarine.hud_position.title", "Sea Scout HUD Position");
        add("nautec.diving_suit.oxygen", "Oxygen: %s minutes %s seconds");
        add("nautec.diving_suit.refill", "Can be filled up using Bottles of pressurized air");
        add("nautec.tool.no_power", "Not enough power");
        add("nautec.tool.ability_enabled", "Ability Enabled");
        add("nautec.tool.ability_disabled", "Ability Disabled");
        add("nautec.network.action_failed", "Action failed: %s");

        add("nautec.tooltip.liquid.amount", "%s mB");
        add("nautec.tooltip.liquid.amount_with_capacity", "%s / %s mB");
        add("nautec.edible","Edible");
        add("nautec.armor.ability.desc", "Ability: Increases protection when powered");
        add("nautec.armor.power", "Power: ");
        add("nautec.armor.status", "Status: ");
        add("nautec.armor.enabled", "Enabled");
        add("nautec.armor.disabled", "Shift + Right Click to Enable");
        add("nautec.helm.desc", "Allows you to see better underwater.");
        add("nautec.neptunes_trident.returns", "Returns to owner");
        add("nautec.tool.axe.ability", "Ability: Chop Down Entire Trees");
        add("nautec.tool.hoe.ability", "Ability: Till 3x3 Farmland");
        add("nautec.tool.pickaxe.ability", "Ability: Mine in a 3x3 Area");
        add("nautec.tool.shovel.ability", "Ability: Mine in a 3x3 Area");
        add("nautec.tool.sword.ability", "Ability: Deal 70% more damage and spawn lightnings at targets");
        add("nautec.tool.infuse-me", "Infuse in Algae Serum to unlock Abilities");
        add("nautec.tool.status", "Status: ");
        add("nautec.tool.power", "Power: ");
        add("nautec.tool.enabled", "Enabled");
        add("nautec.tool.disabled", "Shift + Right Click to Enable");

        add("block.nautec.brown_polymer_block", "Brown Polymer Block");

        add("config.jade.plugin_nautec.mixer", "Mixer");
        add("config.jade.plugin_nautec.aquatic_catalyst", "Aquatic Catalyst");
        add("config.jade.plugin_nautec.laser_junction", "Laser Junction");

        add("nautec.jei.category.aquatic_catalyst_channeling", "Aquatic Catalyst Channeling");
        add("nautec.jei.category.augmentation_effects", "Augmentation Effects");
        add("nautec.jei.category.bacteria_grafting", "Bacteria Grafting");
        add("nautec.jei.category.bacteria_incubation", "Bacteria Incubation");
        add("nautec.jei.category.bacteria_mutations", "Bacteria Mutations");
        add("nautec.jei.category.bio_reactor", "Bio Reactor");
        add("nautec.jei.category.colony_feeding", "Colony Feeding");
        add("nautec.jei.category.item_etching", "Item Etching");
        add("nautec.jei.category.item_transformation", "Item Transformation");
        add("nautec.jei.category.mixing", "Mixing");
        add("nautec.jei.category.eas_infusion", "EAS Infusion");
        add("nautec.jei.eas_infusion.hint", "Leave in an EAS source for %ss");
        add("nautec.jei.info.eas", "EAS is made in the Mixer from Salt Water. Leave an Aquarine Steel tool in an EAS source block for 7.5 seconds to infuse it and unlock its ability; this uses up the source block. An EAS Bucket and three Glass Vials craft into three EAS Vials.");
        add("nautec.grafting_tool.dish_occupied", "This Petri Dish already holds a colony");
        add("nautec.showcase.sign.blocks", "Blocks");
        add("nautec.showcase.sign.multiblocks", "Multiblocks");
        add("nautec.showcase.sign.items", "Items");
        add("nautec.showcase.sign.laser", "Laser Power");
        add("nautec.showcase.sign.iron", "Iron Production");
        add("nautec.showcase.sign.ap", "%s AP");
        add("nautec.showcase.done", "Built the NauTec showcase: %s blocks and %s items over %s by %s blocks");
        add("nautec.showcase.failed", "Could not build the showcase: %s");
        add("nautec.showcase.height", "There is not enough build height here for the showcase");

        for (ResourceKey<?> key : bacterias()) {
            addDirectBacteria(key);
        }

        for (String name : BacteriaMaterials.SHIPPED_NAMES) {
            add("bacteria." + Nautec.MODID + "." + name, Utils.prettify(name));
        }
    }

    private void addFluidType(Supplier<? extends FluidType> fluidType, String val) {
        add(Utils.registryTranslation(NeoForgeRegistries.FLUID_TYPES, fluidType.get()).getString(), val);
    }

    private void curiosIdent(String key, String val) {
        add("curios.identifier." + key, val);
    }

    private void addItem(String key, String val) {
        add("item.nautec." + key, val);
    }

    private void addBacteria(ResourceKey<?> key, String val) {
        add(key.registry().getPath() + "." + key.identifier().getNamespace() + "." + key.identifier().getPath(), val);
    }

    private void addDirectBacteria(ResourceKey<?> key) {
        add(key.registry().getPath() + "." + key.identifier().getNamespace() + "." + key.identifier().getPath(),
                Utils.prettify(key.identifier().getPath()));
    }

    private void addBlock(String key, String val) {
        add("block.nautec." + key, val);
    }
}
